default:
  downloader: aria2
  rss: 0

rss:
  - url1
  - url2

animation:
  不时轻声地以俄语遮羞的邻座艾莉同学:
    episode: 
    whitelist: 不时轻声地以俄语遮羞的邻座艾莉同学
    downloader: aria2
    rss: 1

  test:
    episode: 1,2,3
    whitelist:
    rss:


