default:
  downloader: aria2
  rssindex: 0

rss:
  - https://mikanani.hacgn.fun/RSS/MyBangumi?token=eoz1ajGuXAaU7LmsDmWKMw%3d%3d
  - https://nyaa.si/?page=rss&q=Dungeon+Meshi&c=0_0&f=0

animation:
  Dungeon Meshi:
    episode: 23,22,21,20,19,18,17,16,15,14,13,12,11,10,09,08,07,06,05,04,03,02,01
    whitelist: Dungeon Meshi,迷宫饭
    downloader: aria2
    rssindex: 1
  GIRLS BAND CRY:
    blacklist: 繁
    episode: 1,2,3,4,5,6,7,8,9,10
    whitelist: GIRLS BAND CRY,哭泣少女乐队
  吹响吧! 上低音号 第三季:
    blacklist: 繁
    episode: 1,2,3,4,5,6,7,8,9,10
    whitelist: 吹响,Euphonium,Hibike,上低音号,悠风号
  为美好的世界献上祝福！第三季:
    episode: 1,2,3,4,5,6,7,8,9
    whitelist: 为美好的世界献上祝福
  摇曳露营△ 第三季:
    episode: 1,2,3,4,5,6,7,8,9,10
    whitelist: 摇曳露营,Yurn,Camp 

