default:
  downloader: aria2
  rssindex: 0

rss:
  - https://mikanani.hacgn.fun/RSS/MyBangumi?token=eoz1ajGuXAaU7LmsDmWKMw%3d%3d

animation:
  不时轻声地以俄语遮羞的邻座艾莉同学:
    episode: 
    whitelist: 不时轻声地以俄语遮羞的邻座艾莉同学
    downloader: aria2
    rssindex: 0

